# Generated by Django 3.1.1 on 2020-09-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_link', models.CharField(max_length=150)),
                ('new_link', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Shortened',
        ),
    ]
