# Generated by Django 3.1.1 on 2020-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20200926_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='new_link',
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='old_link',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='full_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(default='', max_length=25),
        ),
    ]
